version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hugs_postgres_db
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hugs_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugs_web
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 hugs.asgi:application"
    env_file:
      - ./local.env
    volumes:
      - .:/usr/src/app/
      - media_volume:/usr/src/app/media/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  media_volume:

